### ISSUE TITLE
license terms

### ISSUE THREAD

**Issue by bourgesl** [tonsky/java-graphics-benchmark#3]
Hi do you agree to submit openjfx bug reports to fix canvas clip ?

Please define your license ?
 If gpl2, I can reuse your ClipDemo code to make a simpler reproducer

**Comment by binarynoise** [comment]
@tonsky 
It would be really great if you added an open source licence to this project.

**Comment by tonsky** [comment]
Added MIT license

**Comment by binarynoise** [comment]
Thank you
